### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by bhaktanishant** [nishanthvijayan/Zebpay-Bitcoin-Price-Indicator#1]
While running this, I am getting exception stating "**No JSON object could be decoded**".

**Here is what I am getting in console;**

```
bitcoinIndicator.py:4: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GLib
bitcoinIndicator.py:6: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as AppIndicator
No JSON object could be decoded
```

**Comment by dhirajdhule** [comment]
replace urlopen module with requests

add this line at the top
from requests import get
then in handler_timeout function edit the try block

data = get(
                    'https://www.zebapi.com/api/v1/market/ticker/btc/inr'
                ).json()
            buy_price = data['buy']
            sell_price = data['sell']

**Comment by bhaktanishant** [comment]
The problem occurred due to gZip compression. So I added gZip support in the code and have applied for pull request. you can find it in my repository.
